// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pelzlKKeUzL939bdWoQt-n0KTUrlM1I',
    appId: '1:549359441886:web:5bb869619cbcc08258ef4f',
    messagingSenderId: '549359441886',
    projectId: 'amina-8af07',
    authDomain: 'amina-8af07.firebaseapp.com',
    storageBucket: 'amina-8af07.firebasestorage.app',
    measurementId: 'G-FPZ7JSH06V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXLk8DMwh9gAYbjhayTv1CemNcnOAqYaI',
    appId: '1:549359441886:android:1ba9644cd2e388a058ef4f',
    messagingSenderId: '549359441886',
    projectId: 'amina-8af07',
    storageBucket: 'amina-8af07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUHKpK2BFETe6BcdiwcCbcfZmo0chMy8',
    appId: '1:549359441886:ios:65ff73685d9b742858ef4f',
    messagingSenderId: '549359441886',
    projectId: 'amina-8af07',
    storageBucket: 'amina-8af07.firebasestorage.app',
    iosBundleId: 'com.example.untitledvoir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUHKpK2BFETe6BcdiwcCbcfZmo0chMy8',
    appId: '1:549359441886:ios:65ff73685d9b742858ef4f',
    messagingSenderId: '549359441886',
    projectId: 'amina-8af07',
    storageBucket: 'amina-8af07.firebasestorage.app',
    iosBundleId: 'com.example.untitledvoir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4pelzlKKeUzL939bdWoQt-n0KTUrlM1I',
    appId: '1:549359441886:web:af3eece0ad307c7958ef4f',
    messagingSenderId: '549359441886',
    projectId: 'amina-8af07',
    authDomain: 'amina-8af07.firebaseapp.com',
    storageBucket: 'amina-8af07.firebasestorage.app',
    measurementId: 'G-V32ZR733BM',
  );
}
